version: '3.3'
services:
  strapi:
    image: cc861010/wlisp:latest
    environment:
      token: xxxxxxxxx # or development
    ports:
      - '80:8080'
    volumes:
      - ${WEBAPP_STORAGE_HOME}/:/home/
    restart: always